CREATE TABLE `test_table_1` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `bit` BIT,
    `bool` BOOL,
    `tinyint` TINYINT UNSIGNED,
    `smallint` SMALLINT UNSIGNED,
    `mediumint` MEDIUMINT UNSIGNED,
    `int` INT UNSIGNED,
    `bigint` BIGINT UNSIGNED,
    `decimal` DECIMAL(10,2),
    `float` FLOAT(10,2),
    `double` DOUBLE(10,2),
    `date` DATE,
    `datetime` DATETIME,
    `timestamp` TIMESTAMP,
    `time` TIME,
    `year` YEAR,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `char` CHAR,
    `varchar` VARCHAR(255),
    `binary` BINARY,
    `varbinary` VARBINARY(255),
    `tinyblob` TINYBLOB,
    `blob` BLOB,
    `mediumblob` MEDIUMBLOB,
    `longblob` LONGBLOB,
    `tinytext` TINYTEXT,
    `text` TEXT,
    `mediumtext` MEDIUMTEXT,
    `longtext` LONGTEXT,
    `enum` ENUM('option1', 'option2', 'option3'),
    `set` SET('option1', 'option2', 'option3'),
    PRIMARY KEY (id)
);
