CREATE SEQUENCE "test_table_1_id_seq";
CREATE TABLE "test_table_1" (
    "id" INTEGER DEFAULT nextval('test_table_1_id_seq') NOT NULL,
    "bit" BIT,
    "bool" BOOL,
    "tinyint" SMALLINT,
    "smallint" SMALLINT,
    "mediumint" INTEGER,
    "int" INT,
    "bigint" BIGINT,
    "decimal" DECIMAL(10,2),
    "float" FLOAT(10),
    "double" DOUBLE PRECISION,
    "date" DATE,
    "datetime" TIMESTAMP,
    "timestamp" TIMESTAMP,
    "time" TIME,
    "year" INTERVAL YEAR,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "char" CHAR,
    "varchar" VARCHAR(255),
    "binary" bytea,
    "varbinary" bytea,
    "tinyblob" bytea,
    "blob" bytea,
    "mediumblob" bytea,
    "longblob" bytea,
    "tinytext" TEXT,
    "text" TEXT,
    "mediumtext" TEXT,
    "longtext" TEXT,
    PRIMARY KEY (id)
);
